/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.InputMap;
import static javax.swing.JComponent.WHEN_FOCUSED;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Anshul
 */
public class Search extends javax.swing.JInternalFrame {
String stt;
static ArrayList arr123=new ArrayList();
    
    
      DefaultTableModel dtz=new DefaultTableModel();
    JTable table=new JTable(); JTable table123z=new JTable();
 int selectedRow;
 static String a_m_d;
 DefaultTableModel dt=new DefaultTableModel();
    /**
     * Creates new form Search
     */
    public Search() {
       
        initComponents();
         this.getRootPane().setDefaultButton(jButton1);
         InputMap im = jButton5.getInputMap(WHEN_FOCUSED);

im.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false), "pressed");
im.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true), "released");
 InputMap im1 = jButton3.getInputMap(WHEN_FOCUSED);

im1.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false), "pressed");
im1.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true), "released");
         jButton3.setVisible(false);
      
         jButton5.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Search Patients");
        setToolTipText("Search Patients");
        setFrameIcon(null);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.lightGray)));

        jButton1.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/imageedit_1_4334984652.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.lightGray)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText(" ID / Name / Mobile");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray), "Patient's Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 0, 14))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton3.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/imageedit_1_3664696261.png"))); // NOI18N
        jButton3.setText(" New Appointment");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.lightGray));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/imageedit_5_6284680653.png"))); // NOI18N
        jButton5.setText(" Reschedule");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.lightGray), "Valid Appointments", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 0, 14))); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(73, 73, 73))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
  stt=table.getValueAt(table.getSelectedRow(),table.getSelectedColumn()).toString();

        selectedRow = table.getSelectedRow();

        if(selectedRow != -1 && ( "Client ID".equals(table123z.getColumnName(table123z.getSelectedColumn()))||"Client ID".equals(table.getColumnName(table.getSelectedColumn())))) { 
    
             Entry.identification=Integer.parseInt(stt);      
              JDesktopPane jp=getDesktopPane();

Add_Appointments ds=new Add_Appointments();
jp.add(ds);

ds.setVisible(true);
this.dispose();} else{
         
        
        JOptionPane.showMessageDialog(null, "Select Client Id From Patient's Details");
        
        }
} catch(Exception e)


{
    
    JOptionPane.showMessageDialog(null,"Please Select Client Id From Patient's Details ");
}
             
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    
         try   {
        
          stt=table123z.getValueAt(table123z.getSelectedRow(),table123z.getSelectedColumn()).toString();


       
        selectedRow = table123z.getSelectedRow();
        if(selectedRow != -1 &&  "App ID".equals(table123z.getColumnName(table123z.getSelectedColumn()))) { 
    
             Entry.identification=Integer.parseInt(stt);
         JDesktopPane jp1=getDesktopPane();

Resc_appo ds1=new Resc_appo();
jp1.add(ds1);

ds1.setVisible(true);
this.dispose();

         // JOptionPane.showMessageDialog(null, stt);
        
        }
        else {
        
        JOptionPane.showMessageDialog(null, "Select App ID");
       
        } } catch (Exception e11) {
            // if(jTextField1.getText().trim().equals(""))
            JOptionPane.showMessageDialog(null,"Please Choose App ID");
           } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(jTextField1.getText().length()!=0)
        { dt.getDataVector().removeAllElements();

            dt.fireTableDataChanged();
            int counter=0;
            jPanel2.removeAll();
            jPanel3.removeAll();
            String [] cn_name={"S.No","Client ID","Client Name","Father's Name","Mobile Numer"};//table 1
            dt.setColumnIdentifiers(cn_name);
            table.setModel(dt);
            table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            table.setFillsViewportHeight(true);
            JScrollPane scroll = new JScrollPane(table);
            scroll.setHorizontalScrollBarPolicy(
                JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            scroll.setVerticalScrollBarPolicy(
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
            int tempo=0;
            try {
                Class.forName("com.mysql.jdbc.Driver");//loads driver
                String url="jdbc:mysql://localhost/hms?user=root&password=india@123";
                Connection cn=DriverManager.getConnection(url); //connection established

                String q="Select * from registration  where ID='"+jTextField1.getText()+"' or c_name='"+jTextField1.getText()+"' or email='"+jTextField1.getText()+"' ";
                PreparedStatement st=cn.prepareStatement(q);

                ResultSet rs=  st.executeQuery();
                while (rs.next()){
                    counter++;
                    rtrnd_name rte=new rtrnd_name();
                    tempo=rs.getInt(1);

                    dt.addRow(new Object[]{counter,rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(5)});
                    //display table 1

                }

            } catch (Exception e) {
                // if(jTextField1.getText().trim().equals(""))
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

            jPanel2.add(scroll);
            jPanel2.validate();
            dtz.getDataVector().removeAllElements();

            dtz.fireTableDataChanged();
            String [] cnz_name={"S.No","App ID","Client ID","Doctor ","Department","Application Date","Validity Date"};//table 2
            dtz.setColumnIdentifiers(cnz_name);
            table123z.setModel(dtz);
            table123z.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            table123z.setFillsViewportHeight(true);
            JScrollPane scrollz = new JScrollPane(table123z);
            scrollz.setHorizontalScrollBarPolicy(
                JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            scrollz.setVerticalScrollBarPolicy(
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
            int cc=0;
            try {
                Class.forName("com.mysql.jdbc.Driver");//loads driver
                String url11="jdbc:mysql://localhost/hms?user=root&password=india@123";
                Connection cn11=DriverManager.getConnection(url11); //connection established

                String q11="Select * from appointment  where c_id='"+tempo+"'and a_mode='new' ";
                PreparedStatement st11=cn11.prepareStatement(q11);

                ResultSet rs11=  st11.executeQuery();
                while(rs11.next()){
                    rtrnd_name rt1=new rtrnd_name();cc++;
                  //  JOptionPane.showMessageDialog(null, "Client id"+tempo+"dr id"+rs11.getInt(4));
                    rt1.client_date(tempo,rs11.getInt(4),dtz,rs11.getInt(1));
                    a_m_d=rs11.getString(11);

                }
               // JOptionPane.showMessageDialog(null,cc);
                rtrnd_name.counterq=cc;
                if(cc!=0&& Reception.Search_==1){
                    jButton3.setVisible(true);
                    jButton5.setVisible(true);
                }else if (cc==0&& Reception.Search_==1){

                    jButton3.setVisible(true);

                }

            } catch (Exception e11) {
                // if(jTextField1.getText().trim().equals(""))
                JOptionPane.showMessageDialog(null, e11.getMessage());
            }

            jPanel3.add(scrollz);

            jPanel3.validate();

            jTextField1.setText("");
            if(table.getRowCount()==0&&table123z.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"No Records");
            }

        }else {

            JOptionPane.showMessageDialog(null,"Field Empty");

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
